// Copyright 2022 Silvan Teufel / Teufel-Engineering.com All Rights Reserved.

#include "Interfaces/CapturePointInterface.h"

// Note: BlueprintNativeEvent functions in interfaces are auto-generated by Unreal.
// Default implementations are provided by the implementing classes (e.g., AWOTACapturePoint).

